### PR TITLE
Update pl_PL.lang

### PR DESCRIPTION
**Pull request by nister6000**

### CODE REVIEW

**Comment by Vierkantor** [comment]
> -tip.PipeFluidsCobblestone=Podstawowa rura\nNie łączy się z kamieniem
> +tip.PipeFluidsCobblestone=Podstawowa rura\Nie łączy się z kamieniem

Your translation seems to check out, but there is a problem: those `n` characters are actually required for the escape code `\n` that begins a new line in the tooltip. Could you add them back in and send in the updated version?

**Comment by nister6000** [comment]
Ah yes i was wondering what it is

**Comment by nister6000** [comment]
What about this? its fixed now.

**Comment by Vierkantor** [comment]
That works! Thanks for your translations!

**Pull request merged**
