### PR TITLE
fix typo(zh_TW.lang): 台 -> 檯

### PR DESCRIPTION
**Pull request by yxliang01**
According to http://chardb.iis.sinica.edu.tw/meancompare/53F0/6AAF , 檯 means table while 台 doesn't have such meaning (in Traditional Chinese).

### CODE REVIEW

**Comment by yxliang01** [comment]
Ping @Vierkantor @tambry  . This has been hanging for almost 3 months(also other PRs). Potentially, you guys want to include more new maintainers?

**Comment by tambry** [comment]
Is this repository still even used for translations?

I haven't done anything related to BuildCraft probably for more than 4 years, so I'd be glad to be removed as a maintainer.

**Comment by yxliang01** [comment]
hmm from https://github.com/BuildCraft/BuildCraft , looks like that repo is still being maintained and it has submodule linked to this repo. So, this repo should still be used? It is more or less expected that not every maintainer can assess most of the translations though :joy: (Who knows so many human languages)
But, if you guys ever need people to assess the Chinese translations (i.e. zh_CN and zh_TW), I'm happy to provide help though.

**Comment by AlexIIL** [comment]
@tambry I'm so sorry, I haven't talked to anyone in the translation team about anything, nor have I responded to any PRs on here since taking maintainership. Are you allowed to remove yourself from the "Translator" team, or would you like me to?

@yxliang01 if you would that would be very helpful!

**Comment by yxliang01** [comment]
@AlexIIL Yup, I'm happy to help with the Chinese translations(among all these translations, I am only good enough for the zh_CN and zh_TW languages) :D 
Thanks for making buildcraft also, although it at times crashes my server, it indeed makes lots of fun until the crashings were worthy.

**Comment by tambry** [comment]
@AlexIIL I've removed myself from the organization. Best of luck!

**Pull request merged**
